Test views
cobbler/cobbler pull request #2408
Opened 2020-09-14 17:30 UTC by bowlerct

Added tests for django views

2020-09-15 07:35 UTC, SchoolGuy approved these changes
I will hit the LGTM button for this so hard that my mouse probably breaks. This is huge! Thanks!

2020-09-15 13:18 UTC, dansou901 commented on tests/views/actions_view_test.py
> +# Test action requests in view. These test the website operation
"These tests"...

2020-09-15 13:20 UTC, dansou901 commented on tests/views/actions_view_test.py
> +# Test action requests in view. These test the website operation
"Tests action..."

2020-09-15 13:21 UTC, dansou901 commented on tests/views/list_items_view_test.py
> +# Test listing of items
"Tests listing of items"

2020-09-15 13:22 UTC, dansou901 requested changes
See inline comment

2020-09-15 15:23 UTC, bowlerct commented on tests/views/list_items_view_test.py
> +# Test listing of items
updated

2020-09-15 15:29 UTC, dansou901 approved these changes
LGTM now.

2020-09-16 07:36 UTC, hbokh approved these changes
If it works, it works!! LGTM

2020-09-16 10:16 UTC, merged