Switch to build system according to PEP 517/518
cobbler/cobbler pull request #2414
Opened 2020-09-18 13:16 UTC by nodeg

This PR will fix #2412. I had to add the `wheels` package, otherwise pip would not stop complaining:

```shell
$ pip install .                                                                                                                                                       
Processing /home/dom/git/work/cobbler                                                                                                                                         
  Installing build dependencies ... done                                                                                                                                      
  WARNING: Missing build requirements in pyproject.toml for file:///home/dom/git/work/cobbler.                                                                                
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
(...)
```
The [pip documentation](https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support) confirms that.
> If a project has [build-system], but no build-backend, pip will also use setuptools.build_meta:__legacy__, but will expect the project requirements to include setuptools and wheel (and will report an error if the installed version of setuptools is not recent enough).

2020-09-18 13:21 UTC, brejoc approved these changes
lgtm!

2020-09-18 14:50 UTC, dansou901 approved these changes
LGTM!

2020-09-18 19:17 UTC, watologo1 commented
Would be nice if Neal could have a look at this. He has quite some background in python package building.

2020-09-18 19:18 UTC, Conan-Kudo commented
This will break building on EL7, as pip there is too old and doesn't know about PEP 517/518.

2020-09-18 19:19 UTC, Conan-Kudo requested changes
This doesn't seem to provide any significant value. What are you trying to accomplish here?

2020-09-18 20:18 UTC, SchoolGuy commented
@Conan-Kudo The thing is that currently if the dependencies for the installation are not installed manually the installation just errors out. With this change this is not the case anymore.

2020-09-18 20:19 UTC, Conan-Kudo commented
@SchoolGuy Yes, but they're there because you're importing and using them _in_ the setuptools scripts. They're not there for no reason...

2020-09-18 20:21 UTC, SchoolGuy commented
@Conan-Kudo Yes that's right and if we do it like this PR suggests then we could solve this because pip would install everything for us before the installation. So we would have a `pip install .` working with no extra steps if I understand this correctly...

2020-09-18 20:25 UTC, Conan-Kudo commented
That's pretty broken, though. We define these because we need them.

2020-09-18 20:31 UTC, SchoolGuy commented
Yeah and now we would define them differently... 😅

2020-09-18 20:44 UTC, Conan-Kudo commented
I don't think this is a good idea, since it means that for most flows, this would be ignored and it would be broken...

2020-09-19 05:43 UTC, SchoolGuy commented
@Conan-Kudo Then what is your proposed idea to make it possible to do a `pip install .` without problems.

2020-09-21 07:41 UTC, nodeg commented
@Conan-Kudo I understand your concerns regarding EL7 which has only pip 9.0 available. So I will close this PR and leave only the issue open and maybe we can solve the problem with adjusting the Makefile and creating a new target there.

2020-09-21 07:41 UTC, closed without merging

2020-09-23 07:57 UTC, watologo1 commented
Would something like this help?
Use requirements.txt for setup.py install_requires

https://github.com/openSUSE/orthos2/commit/53aec1b040a2bf4f68a5aca208d8c4d1e63fab41

2020-09-23 10:13 UTC, Conan-Kudo commented
No, because the problem is that this `setup.py` requires importing external modules to run, which is why it has `setup_requires`.