WIP: Tests: Add tests for utils.py
cobbler/cobbler pull request #2420
Opened 2020-10-02 17:01 UTC by SchoolGuy

Since `utils.py` is kind of an import part of our project I wanted to explicitly test everything we have in there to keep it stable and working. Since this is kind of a mad file regarding the length it will take a while until it is ready.

2020-10-08 11:03 UTC, watologo1 requested changes
Are all these tiny unusued utils tests needed?
Why and where?

2020-10-08 11:03 UTC, watologo1 commented on tests/utils_test.py
> +def test_pretty_hey():
test_pretty_hex?

2020-10-08 15:22 UTC, watologo1 commented
It would also be better to split this in fixes and and the new tests (file).
Beside the one "r" that slipped in, these fixes can/should just go in.

2020-10-08 18:59 UTC, SchoolGuy commented
@watologo1 The didn't slip in. It was put there intentional since this is now a raw docstring which enables Python to handle the docstring differently. The fixes and the tests are dependent. Since I am not rewriting a whole module I would like to keep this together. Also this is not finished and this the empty calls.

2020-10-09 13:05 UTC, hbokh commented
@SchoolGuy Any idea what is happening here?
https://travis-ci.com/github/cobbler/cobbler/jobs/395116973#L1929-L1932

2020-10-09 13:08 UTC, SchoolGuy commented
@hbokh Nope but I will have a look locally and push a fix later.

2020-10-09 13:41 UTC, SchoolGuy commented on tests/utils_test.py
> +def test_pretty_hey():
Will be fixed with the next commit.

2020-10-09 13:41 UTC, SchoolGuy commented on cobbler/utils.py
> +    r"""
That is intentional as this is then a raw docstring.

2020-10-13 13:33 UTC, SchoolGuy commented
@watologo1 @hbokh @dansou901 @Conan-Kudo @loreson I would love if we could review this rather sooner then later. I will clean up the git history in the next few minutes so the CI will run again.

2020-10-13 13:47 UTC, dansou901 commented
@SchoolGuy I won't be of much help reviewing this, as I don't speak python. I'm leaving this one to the others.

2020-10-13 13:51 UTC, SchoolGuy commented
@nodeg & @m-rey your opinions are also valid in this matter I think, although you currently don't belong to the project officially.

2020-10-14 01:19 UTC, opoplawski commented
I don't have much to add other that I'm glad that folks are writing tests.

2020-10-15 12:00 UTC, nodeg requested changes
I left some suggestions.

2020-10-15 13:04 UTC, SchoolGuy commented on cobbler/utils.py
> +    :param quiet: If "True" no progress is reported. If ``False`` then progress will be reported by rsync.
Will be fixed in the next commit.

2020-10-15 13:04 UTC, SchoolGuy commented on cobbler/utils.py
> +    :param item_dict: The dictionary representation of a Cobbler Item.
Will be fixed in the next commit.

2020-10-15 13:04 UTC, SchoolGuy commented on cobbler/utils.py
> +
I removed the comment line. It makes no sense indeed.

2020-10-15 13:04 UTC, SchoolGuy commented on cobbler/utils.py
> +
This makes no sense indeed.

2020-10-15 13:05 UTC, SchoolGuy commented on tests/utils_test.py
> +    # Pre Assert to check that this actually does something
Will be fixed in the next commit.

2020-10-15 13:05 UTC, SchoolGuy commented on tests/utils_test.py
> +    # TODO: Assert file exists on the cache destination
Will be fixed in the next commit.

2020-10-15 13:06 UTC, SchoolGuy commented on tests/utils_test.py
> +    # TODO: How the heck to we check this actually did what it is supposed to do?
Will be fixed in the next commit.

2020-10-15 13:07 UTC, SchoolGuy commented on tests/utils_test.py
> +    # work this is smaller then 0. The content is a yaml file thus we don't want to test if writing a yaml file is
Will be fixed in the next commit.

2020-10-15 13:14 UTC, SchoolGuy commented
Codacy may fail since the subprocess calls are intentional and we havn't had the time to configure the other linters regarding the Doc Comment styles.

2020-10-15 17:32 UTC, watologo1 approved these changes
IMO changing comments to raw strings to show code elements:
""" dict() is a method

to
r""" ``dict()`` is a method

is IMO somewhat overdosed. Just keep the rest. There is more important things to do...
The submitrequest looks fine and correct to me. If, then maybe too correct ;)

2020-10-16 07:05 UTC, nodeg approved these changes
LGTM.

2020-10-16 07:05 UTC, SchoolGuy commented
Since we two approvals. I will merge now.

2020-10-16 07:06 UTC, merged