Document Terraform provider
cobbler/cobbler pull request #2528
Opened 2021-01-30 16:01 UTC by hbokh

This is a "replacement" for #2283.

Written with Cobbler 3.2.x and Terraform v0.14.x in mind.

2021-01-30 16:05 UTC, hbokh commented
Preview: https://cobbler--2528.org.readthedocs.build/en/2528/user-guide/terraform-provider.html

2021-01-30 19:44 UTC, SchoolGuy approved these changes
LGTM in my eyes. Thanks @hbokh !

2021-02-01 11:08 UTC, dansou901 requested changes
See inline comments

2021-02-01 11:08 UTC, dansou901 commented on docs/user-guide/terraform-provider.rst
> +     # NOTE: Extra spaces at the end is there for a reason!
Extra spaces at the end are there for a reason

2021-02-01 11:08 UTC, dansou901 commented on docs/user-guide/terraform-provider.rst
> +For example, this will combine a Ubuntu Bionic distro, a profile and a system:
this will combine an Ubuntu Bionic distro

2021-02-01 13:04 UTC, dansou901 approved these changes
LGTM now.

2021-02-01 15:06 UTC, merged