Add python-schema to our requirements
cobbler/cobbler pull request #2530
Opened 2021-02-01 15:14 UTC by SchoolGuy

This PR shall close #2419 

This PR also tries to pull all application settings related functionality inside the module and remove the factor that we require the file to be exactly at `/etc/cobbler/settings`. I see this as a first step into the direction of of containerized Cobbler.

2021-02-01 15:45 UTC, SchoolGuy commented
Oh and I will try to sneak in some mongodb fixes. They are not important but since I am over that file anyway I won't ignore them. I can't break it more then it is already broken.

2021-02-01 16:16 UTC, SchoolGuy commented
@Conan-Kudo Do we have any way to get https://github.com/keleshev/schema into all required RH distros? I see https://src.fedoraproject.org/rpms/python-schema but apparently this is not everywhere available for RH? openSUSE and Debian an good as far as I can see.

2021-02-01 16:23 UTC, SchoolGuy commented
@dansou901 Can you make something out of this? - https://packages.debian.org/buster/python3-schema and https://github.com/cobbler/cobbler/pull/2530/checks?check_run_id=1808074146#step:3:6141

2021-02-01 16:29 UTC, dansou901 commented
Seems like python3-schema is missing from the apt install step in the Dockerfile. Add that and it should work.

2021-02-02 07:35 UTC, SchoolGuy commented
Nice we have a circular dependency in `utils.py` and `settings.py`. This due to our unused multi-language support. I will remove that completely and will open a Feature Request for that so we can add it when it is useful again.

2021-02-02 09:42 UTC, SchoolGuy commented
Codacy fails, yes this is bad, no I won't do more then I did because this PR is too huge anyway. I will split it later but that still won't fix Codacy. Thus we need to live with the fact that we aren't at a point where linters are useful. We will let them stay enabled because they are a good reminder where we can and need to improve.

2021-02-02 10:13 UTC, SchoolGuy commented
I contacted the maintainer of `python-schema` and asked if it is possible to include this package in EPEL.

2021-02-13 12:43 UTC, SchoolGuy commented
So python-schema has been added to EPEL 8. It is currently in testing but when it is in EPEL 8 fully, CentOS 8 should build also!

2021-02-14 19:02 UTC, SchoolGuy commented
I don't know how to document this but we have to keep in mind that PyYAML can't write comments and can't read them. Thus our documentation in the YAML file will be gone once we write back to config once.

Source: https://github.com/yaml/pyyaml/issues/90

2021-02-16 12:22 UTC, SchoolGuy commented
Rebase onto master and resolve conflict

2021-02-16 12:34 UTC, SchoolGuy commented
Things that need to be done:

- [ ] Check the documentation and create hints so a manual migration of the settings file works
- [ ] Test: Add case so an old settings file is migrated correctly (also from `/etc/cobbler/settings`)
- [ ] Test: Unskip writing the settings file (thus replace it with the default one after the testcases)
- [ ] Code: Actually use the validation and handle errors if the settings file is invalid
- [ ] Test: Write tests with invalid settings files (especially with old style ones)

2021-02-18 15:15 UTC, SchoolGuy commented
While reviewing the docs and related code I discovered that the settings docs are in a very poor state. I will address that along with this PR since it is a rework of our settings module.

2021-02-19 13:35 UTC, brejoc approved these changes
Pretty huge PR, but I haven't seen anything that led me to believe that there is a problem.

2021-02-19 18:56 UTC, SchoolGuy commented
Rebase onto master

2021-02-20 08:09 UTC, SchoolGuy commented
So old style settings are correctly migrated when they had default values before. I guess we need to bite in the apple that very custom settings may produce errors. This means that we need publish hotfix releases and prepare patches for distro maintainers in case anything goes wrong for users.

2021-02-20 10:25 UTC, SchoolGuy commented
CentOS 8 again is making problems since a dependency of `python-schema` is now missing. I will try to fix that with some mails but this is definitely lowering my personal desire to be compatible with CentOS 8 RPMs...

2021-02-20 14:22 UTC, SchoolGuy commented
@opoplawski Would you please be so kind to pull in the dependencies missing for `python-schema` into EPEL? CentOS 8 is kind of new territory for me, your name may open more doors then mine.

2021-02-20 17:27 UTC, SchoolGuy commented
Cleaned Git History

2021-02-20 18:36 UTC, nodeg commented on config/cobbler/settings.d/manage_genders.settings
> +manage_genders: False
```suggestion
manage_genders: false
```

2021-02-20 18:40 UTC, nodeg commented on docs/cobbler-conf.rst
> +There are additional configuration files location which need to follow the YAML Syntax. These are loaded from the
```suggestion
There are additional configuration file locations which need to follow the YAML Syntax. These are loaded from the
```

2021-02-20 18:52 UTC, nodeg commented on docs/cobbler-conf.rst
> +  ``1`` and ``0`` this is fine but may should convert them as soon as possible. We may decide in a future version to
```suggestion
- We require the usage of booleans in the format of ``True`` and ``False``. If you have old integer style booleans with
  ``1`` and ``0`` this is fine but you may should convert them as soon as possible. We may decide in a future version to
```

2021-02-20 18:53 UTC, nodeg commented on docs/cobbler-conf.rst
> +  Cobbler please report this in our Issue Tracker. We have decided to go this way to be able to rely on the existence
```suggestion
  Cobbler please report this in our issue tracker. We have decided to go this way to be able to rely on the existence
```

2021-02-20 18:54 UTC, nodeg commented on docs/cobbler-conf.rst
> +If "True", Cobbler will allow insertions of system records that duplicate the IP address information of other system
```suggestion
If ``True``, Cobbler will allow insertions of system records that duplicate the IP address information of other system
```

2021-02-20 18:57 UTC, nodeg commented on docs/cobbler-conf.rst
> +The location where Cobbler searches for Grub configuration files.
```suggestion
The location where Cobbler searches for GRUB configuration files.
```

2021-02-20 18:58 UTC, nodeg commented on docs/cobbler-conf.rst
> +- enabled: set to ``True`` to turn this feature on
```suggestion
- enabled: Set to ``True`` to turn this feature on
```

2021-02-20 18:58 UTC, nodeg commented on docs/cobbler-conf.rst
>  - sender: optional
```suggestion
- sender: Optional
```

2021-02-20 18:59 UTC, nodeg commented on docs/cobbler-conf.rst
> +    build_reporting_enabled: False
```suggestion
    build_reporting_enabled: false
```

2021-02-20 19:02 UTC, nodeg commented on docs/cobbler-conf.rst
> +persisted across reboots and can be easily thrown away but is also fast.
```suggestion
Used for caching the intermediate files for ISO-Building. You may want to use a SSD, a tmpfs or something which does not
persist across reboots and can be easily thrown away but is also fast.
```

2021-02-20 19:04 UTC, nodeg commented on docs/cobbler-conf.rst
> +force commands like Cobbler sync to open a connection to a remote address if one is in the configuration and would
```suggestion
force commands like ``cobbler sync`` to open a connection to a remote address if one is in the configuration and would
```

2021-02-20 19:05 UTC, nodeg commented on docs/cobbler-conf.rst
> +Convert hostnames to IP-addresses (where possible) so DNS isn't a requirement for various tasks to work correctly.
```suggestion
Convert hostnames to IP addresses (where possible) so DNS isn't a requirement for various tasks to work correctly.
```

2021-02-20 19:07 UTC, nodeg commented on docs/cobbler-conf.rst
> +          the code. Thus please try to use Jinja2. We will try to support a seamless transition on a best-effort basis.
```suggestion
          the code. Thus, please try to use Jinja2. We will try to support a seamless transition on a best-effort basis.
```

2021-02-20 19:09 UTC, nodeg commented on docs/cobbler-conf.rst
> +    ldap_anonymous_bind: True
```suggestion
    ldap_tls: true
    ldap_anonymous_bind: true
```

2021-02-20 19:09 UTC, nodeg commented on docs/cobbler-conf.rst
> +When using the Bind9 DNS Server, you can enable or disable if the BMCs should receive own DNS entries.
```suggestion
When using the Bind9 DNS server, you can enable or disable if the BMCs should receive own DNS entries.
```

2021-02-20 19:11 UTC, nodeg commented on docs/cobbler-conf.rst
> +Whether or not to manage the Genders file. For more information on that visit:
```suggestion
Whether or not to manage the genders file. For more information on that visit:
```

2021-02-20 19:13 UTC, nodeg commented on docs/cobbler-conf.rst
> +        from_cobbler: True
```suggestion
.. code-block:: YAML

    mgmt_classes: []
    mgmt_parameters:
        from_cobbler: true
```

2021-02-20 19:14 UTC, nodeg commented on docs/cobbler-conf.rst
> +This enabled or disables the replacement (or removal) of records in the DNS zone for systems created (or removed) by
```suggestion
This enables or disables the replacement (or removal) of records in the DNS zone for systems created (or removed) by
```

2021-02-20 19:18 UTC, nodeg commented on docs/cobbler-conf.rst
> +This setting is only used by the code that supports using Spacewalk/Satellite authentication within Cobbler Web and
```suggestion
This setting is only used by the code that supports using Uyuni/SUSE Manager/Spacewalk/Satellite authentication within Cobbler Web and
```

2021-02-20 19:21 UTC, nodeg commented on docs/cobbler-conf.rst
>  .. code::
```suggestion
.. code:: YAML
```

2021-02-20 19:21 UTC, nodeg commented on docs/cobbler-conf.rst
> +    scm_track_enabled: False
```suggestion
    scm_track_enabled: false
```

2021-02-20 19:21 UTC, nodeg commented on docs/cobbler-conf.rst
>  .. code::
```suggestion
.. code:: YAML
```

2021-02-20 19:21 UTC, nodeg commented on docs/cobbler-conf.rst
> +    restart_dhcp: True
```suggestion
    restart_dns: true
    restart_dhcp: true
```

2021-02-20 19:22 UTC, nodeg commented on docs/cobbler-conf.rst
> +default: ``True``
```suggestion
default: ``true``
```

2021-02-20 19:22 UTC, nodeg commented on docs/cobbler-conf.rst
> +default: ``False``
```suggestion
default: ``false``
```

2021-02-20 19:23 UTC, nodeg commented on docs/cobbler-conf.rst
> +The Cobbler Import workflow is powered by this file. Its location can be set with this config option.
```suggestion
The Cobbler import workflow is powered by this file. Its location can be set with this config option.
```

2021-02-20 19:24 UTC, nodeg commented on docs/cobbler-conf.rst
> +default: ``True``
```suggestion
default: ``true``
```

2021-02-20 19:24 UTC, nodeg commented on docs/cobbler-conf.rst
> +default: ``True``
```suggestion
default: ``true``
```

2021-02-20 19:26 UTC, nodeg commented on docs/cobbler-conf.rst
> +mirrored yum repos are still accessible at ``http://cobbler.example.org/cblr/repo_mirror`` and yum configuration can
```suggestion
mirrored yum repos are still accessible at ``http://cobbler.example.org/cblr/repo_mirror`` and YUM configuration can
```

2021-02-20 19:27 UTC, nodeg commented on docs/cobbler-conf.rst
> +Chooses the TFTP management engine if ``manage_tftpd`` is enabled in ``/etc/cobbler/settings.yaml``, which is ON by
```suggestion
Chooses the TFTP management engine if ``manage_tftpd`` is enabled in ``/etc/cobbler/settings.yaml``, which is **on** by
```

2021-02-20 19:32 UTC, nodeg requested changes
I left some comments.

2021-02-21 05:18 UTC, opoplawski commented
> CentOS 8 again is making problems since a dependency of `python-schema` is now missing. I will try to fix that with some mails but this is definitely lowering my personal desire to be compatible with CentOS 8 RPMs...

I'm committed to making cobbler work on CentOS 8.  I've piled on to request for the needed dep to get added and offered to help out.

2021-02-21 09:46 UTC, SchoolGuy commented
@opoplawski Thanks a lot! That is very great news for me! :)

2021-02-21 13:40 UTC, nodeg commented on cobbler/settings.py
> +        logging.exception("Settingsfile was not returned due to missing Keys.")
```suggestion
        logging.exception("Settings file was not returned due to missing Keys.")
```

2021-02-21 13:41 UTC, nodeg commented on cobbler/settings.py
> +        logging.exception("Settingsfile was returned due to an error in the schema.")
```suggestion
        logging.exception("Settings file was returned due to an error in the schema.")
```

2021-02-21 13:44 UTC, nodeg commented on cobbler/settings.py
> +        logging.exception("Settingsfile was not written to the disc due to missing Keys.")
```suggestion
        logging.exception("Settings file was not written to the disc due to missing keys.")
```

2021-02-21 13:45 UTC, nodeg commented on cobbler/settings.py
> +        logging.exception("Settingsfile was not written to the disc due to an error in the schema.")
```suggestion
        logging.exception("Settings file was not written to the disc due to an error in the schema.")
```

2021-02-21 14:09 UTC, nodeg approved these changes

2021-02-21 14:13 UTC, merged

2021-03-03 00:55 UTC, opoplawski commented
contextlib2 is now in EPEL testing - please provide karma here: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-65e082736e