Grub fixes
cobbler/cobbler pull request #2792
Opened 2021-09-16 10:41 UTC by watologo1

2021-09-16 11:42 UTC, SchoolGuy commented on cobbler/tftpgen.py
> +                    initrd_path = distro._remote_grub_initrd
Never ever access implementation specific attributes outside of the internal scope please! That is what we introduced the properties for. Everything with one or two underscores should be off limits outside of the original module/class.

```suggestion
                if distro.remote_grub_kernel:
                    kernel_path = distro.remote_grub_kernel
                if distro.remote_grub_initrd:
                    initrd_path = distro.remote_grub_initrd
```

2021-09-18 08:14 UTC, nodeg requested changes
The `test_blender()` method in `test_utils.py` has to be adjusted to 150 elements since you removed 2 methods/tests.

2021-09-18 08:14 UTC, nodeg commented on cobbler/modules/managers/isc.py
> +                    self.logger.warning("%s has no IPv6 or MAC address" % system.name)
```suggestion
                    self.logger.warning("%s has no IPv6 or MAC address", system.name)
```

2021-09-19 17:36 UTC, watologo1 commented
@nodeg Thanks! I integrated both suggestions (test for 150, due to 2 parameter removals and use parameter passing instead of string concatenation in logging message).

2021-09-19 19:45 UTC, SchoolGuy requested changes
So we will do a release tomorrow. I won't fix this today though but it will be included in the release.

The change you are proposing is a typical usecase for a readonly property. I change it myself tomorrow. What you did here is suboptimal afaik because you allow external applications to change the value you only want to update internally. Sorry that I wasn't able to look earlier at this and need to change it without your blessing tomorrow.

2021-09-19 19:45 UTC, SchoolGuy commented on cobbler/modules/managers/isc.py
> +                    self.logger.warning("%s has no IPv6 or MAC address" % system.name)
Found a lazy logger call. Or to be more precise Codacy did.

```suggestion
                    self.logger.warning("%s has no IPv6 or MAC address", system.name)
```

2021-09-20 12:27 UTC, SchoolGuy approved these changes
Now LGTM

2021-09-20 12:30 UTC, agraul approved these changes
LGTM

2021-09-20 12:37 UTC, nodeg approved these changes
LGTM.

2021-09-20 12:40 UTC, merged

2021-09-20 12:42 UTC, watologo1 commented
Thanks!