Enhance mkloaders
cobbler/cobbler pull request #2836
Opened 2021-11-11 15:06 UTC by watologo1

2021-11-22 12:48 UTC, SchoolGuy commented on cobbler/actions/mkloaders.py
> +        self.grubconfig_dir = api.settings().grubconfig_dir
Those are paths, so I would love if we could use them also as Path objects. This also ensures then when being cast to a str that they should have a slash either always appended or never. This should prevent things like: `/my/bootloc/path//`

2021-11-22 12:51 UTC, SchoolGuy commented on cobbler/settings/migrations/V3_3_0.py
> +        'x86_64-efi': {'binary_name': 'grubx64.efi', 'extra_modules': ['chain', 'efinet']}}
Please don't touch this file! Please add these changes into a new migration. Old migrations should never change!

2021-11-22 12:53 UTC, SchoolGuy commented on tests/test_data/V3_3_0/settings.yaml
> +    binary_name: grubx64.efi
Same as for the migration. This file should never change! Please add it to the one for the next version and if that doesn't exist please create it!

2021-11-22 12:53 UTC, SchoolGuy requested changes
I left some comments. Please also adjust the tests so we don't let them fail!

2022-02-11 14:17 UTC, watologo1 commented
As discussed, all/most stuff got implemented by Enno already and is in.

2022-02-11 14:17 UTC, closed without merging