[3.2] Backport fix for CVE-2022-0860
cobbler/cobbler pull request #3397
Opened 2023-04-03 02:35 UTC by opoplawski

2023-04-03 09:30 UTC, SchoolGuy commented
@opoplawski I will take care of fixing up your Pull Request description this time but please don't just ignore our workflows. It is very annoying to manually do this for every request. The next time I wish that the Pull Request has a better quality.

2023-04-03 12:45 UTC, SchoolGuy requested changes
The test ensuring that this is working was not backported. Please add the test that was created for this CVE to the backport.

2023-05-01 18:24 UTC, SchoolGuy approved these changes
After the rebase the commit is signed by me. LGTM.

2023-05-01 18:24 UTC, merged

2023-05-03 04:00 UTC, opoplawski commented
Thank you very much for finishing this and other PRs up for me.  I'm afraid I'm just stretched way too thin at the moment.

2023-05-03 06:16 UTC, SchoolGuy commented
@opoplawski Thanks for getting back! Not a problem. I will keep it in mind.