add setting to use a new XMLRPC API endpoint and disable SSL verification
cobbler/cobbler pull request #3629
Opened 2024-02-27 16:47 UTC by mbussolotto

## Linked Items

## Description

add setting to use a new XMLRPC API endpoint and disable SSL verification. This would allow to use cobbler inside a uyuni container. Currently it's not possible cause connection using `redhat_management_server` value (FQDN) cause hairpin problem.

## Behaviour changes

Old: 
`redhat_management_server` was used to set XMLRPC endpoint

New: 
`xmlrpcapi_endpoint` is used to set XMLRPC endpoint
`xmlrpcapi_ignore_certificate` is used to disable SSL verification

## Category

This is related to a:

- [ ] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [x] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

2024-02-28 08:23 UTC, SchoolGuy requested changes
Thanks for the PR! I would like to kindly ask you to do some housekeeping before we proceed with this one.

1. Create an issue with a feature request where the problem is described in companion with the proposed solution.
2. Add a changelog fragment that mentions the created issue along with a short one-liner.
3. Don't forget to also add the new settings to the rst documentation.

Now in regard to the code:

- Please find a much better name for the settings as the name indicates that this has something to do with the XML-RPC API that Cobbler exposes (which is not the case).
- Please correct the docstring for `redhat_management_permissive` in the `settings.yaml` as this is targeting the `relase33` branch. (I believe you didn't mean to touch this at all.)
- The new setting `xmlrpcapi_endpoint` is mapped to `redhat_management_server` essentially. I know it is more effort but then let's make this a mapping where the subkeys are something like `external` and `internal`. Doesn't have to be exactly that but it should be obvious that those two hostnames/IPs both point to the same server, one internally and one externally.

2024-03-01 11:49 UTC, rjmateus commented on cobbler/modules/authentication/spacewalk.py
> +    if api_handle.settings().spacewalk_authentication_endpoint:
The new variable should define the server and method. Fall back (if not defined) should be the exact same behaviour as before, to make sure we don't break any environment.

2024-03-07 16:45 UTC, mbussolotto commented
@meaksh @m-czernek @agraul not sure why I cannot you as reviewer

2024-03-07 17:50 UTC, rjmateus commented
@SchoolGuy I think this PR is ready for review. This is blocking some development from our side. Could I ask for your feedback/review on this one?
Thank you

2024-03-08 09:31 UTC, meaksh approved these changes

2024-03-08 09:40 UTC, rjmateus approved these changes

2024-03-08 15:38 UTC, SchoolGuy requested changes
The name of the setting is really misleading and does not reflect its intended use. I mentioned this in the initial review already.

Spacewalk as a project is not existing anymore. As such the endpoint is exclusive to Uyuni/SUMA. Please either rename this to `uyuni_authentication_endpoint` (even though I am totally against that) or convert `redhat_management_server` into a mapping with subkeys for `internal` and `external`.

The reason I prefer the latter is that this is the only way that would clearly show during usage that these settings are related. Comments are being stripped from the file most of the time because YAML parsers can't restore them when writing back to disk.

As commented internally there was no attempt to synchronize with the creator of https://github.com/cobbler/cobbler/pull/3540 as this is work that is related (as it touched `redhat_management_key` which is critical for Uyuni/SUMA). Neither in a comment of this PR nor over there.

2024-03-08 16:22 UTC, SchoolGuy approved these changes
Not the best solution but as pointed out resources are constrained and as such this is something that I feel comfortable going forward with.

2024-03-08 16:23 UTC, SchoolGuy commented
@mbussolotto Please sign your commits if you have set this up.

2024-03-08 17:31 UTC, mbussolotto commented
I think I cannot merge it (I'm not an authorized used).  Can you please do that ? Thanks

cc @meaksh

2024-03-08 17:43 UTC, SchoolGuy commented
@mbussolotto Of course I will merge it. Waiting for the CI to finish first. :)

2024-03-08 19:07 UTC, merged

2024-03-11 10:37 UTC, agraul commented
I know it's late and I'm okay with keeping it this way, but I still need to point this out:

> The name of the setting is really misleading and does not reflect its intended use. I mentioned this in the initial review already.
> 
> Spacewalk as a project is not existing anymore. As such the endpoint is exclusive to Uyuni/SUMA. Please either rename this to `uyuni_authentication_endpoint` (even though I am totally against that)

The module is still called `cobbler/modules/authentication/spacewalk.py`. As such, `spacewalk_authentication_endpoint` makes perfect sense.