buildiso: Introduce exclude-systems CLI option and distro autodetection
cobbler/cobbler pull request #3665
Opened 2024-03-19 16:03 UTC by aaannz

## Linked Items

Fixes #

 

## Description

This commit makes --distro option optional, if not provided first profile or first system is used to get the distro automatically.

This commit introduces --exclude-systems option. This instructs buildiso to not write any system records entries to the isolinux/grub config. Useful particularly when only profile entries are requested.

## Behaviour changes

Old: `buildiso --distro` is mandatory option. There is no way to export config only for specific profiles if systems exists too.

New: `--distro` is optional, determined from first profile or system if not set. Use `--exclude-systems` to export configuration only for provided profiles.

## Category

This is related to a:

- [ ] Bugfix
- [X] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [X] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

2024-03-20 08:35 UTC, m-czernek reviewed
The code itself looks OK to me, but we need to fix some of the fails:

- Add Black formatting
- Add the missing changelog entry
- Import error that causes the tests to fail (I think that's the same issue as some of the Codacy failures, together with some missing type declaration(s))

That should fix a lot of the CI fails

2024-03-20 12:13 UTC, agraul requested changes
Changes for netboot LGTM!

Could you also add `--exclude-systems` for `buildiso.standalone`?

2024-03-21 13:43 UTC, aaannz commented
About the imports, I see that Distro was there before and is under TYPE_CHECKING condition. So I assume we do not want to have to import Profile and System by default.

Am I correct to instead of e.g. `List[Profile]` add like `List["Profile"]` and add new `Optional` where needed?

2024-03-25 15:45 UTC, SchoolGuy approved these changes
Thank you for this addition. I would argue that the Git commit log could be cleaned up but it is not mandatory in my eyes to merge this PR.

2024-04-22 14:57 UTC, agraul commented
My question still stands, is this something that is also needed for `--standalone`?

2024-05-29 19:36 UTC, SchoolGuy commented
@aaannz Could you maybe clarify with Alex the open discussion please?

2024-10-21 07:36 UTC, SchoolGuy commented
@aaannz Both pyright and Codacy have some valid criticism of your PR. I would kindly ask you to incorporate those suggestions.

2024-10-21 09:24 UTC, aaannz commented
@agraul Added feature also to standalone.

2024-11-12 16:46 UTC, merged