Ensure that the Yum repo file is created in the correct location
cobbler/cobbler pull request #3870
Opened 2024-12-26 13:06 UTC by fallsjo

## Linked Items

Fixes #3704 (at least this I think it is the same bug I had)

 

## Description

Changes how the file path is created with respect to the webdir setting.
The original code started with an explicit "/" thus trashing all existing path components.
With this change the individual components should be added to the relative setting as expected.

## Behaviour changes

Old: The file is not generated, possibly due to being created in the wrong location with insufficient permissions and/or missing parent directories.

New: The .repo file is created where expected.

## Category

This is related to a:

- [x] Bugfix
- [ ] Feature
- [ ] Packaging
- [ ] Docs
- [ ] Code Quality
- [ ] Refactoring
- [ ] Miscellaneous

## Tests

- [ ] Unit-Tests were created
- [ ] System-Tests were created
- [ ] Code is already covered by Unit-Tests
- [ ] Code is already covered by System-Tests
- [ ] No tests required

2025-01-29 14:36 UTC, SchoolGuy requested changes
Could we please create a test that verifies that this code continues to work with future changes? I am not very close with that code and would love to get help with creating a test.

2025-01-29 14:44 UTC, fallsjo commented
Same here, I can take a look…

/JockeF

> On 29 Jan 2025, at 16:37, Enno G. ***@***.***> wrote:
> 
> 
> @SchoolGuy requested changes on this pull request.
> 
> Could we please create a test that verifies that this code continues to work with future changes? I am not very close with that code and would love to get help with creating a test.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/cobbler/cobbler/pull/3870#pullrequestreview-2581258432>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFCTP6VUSODL6XNGZTY5VN32NDRSDAVCNFSM6AAAAABUHGVV4WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKOBRGI2TQNBTGI>.
> You are receiving this because you authored the thread.
>

2026-08-26 15:45 UTC, SchoolGuy approved these changes

2026-08-26 15:52 UTC, SchoolGuy commented
GH CI seems to hang again. I verified the test works locally.

2026-08-26 15:52 UTC, merged